site_name: Tad Zeila Book
theme:
  name: material
  logo: logo/cat_white.png
  text: Noto Serif Medium
  code: Roboto Mono Medium
  highlightjs: true
  hljs_style: github
  hljs_style_dark: github-dark
  palette:
  - scheme: default
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-4
      name: Switch to dark mode
  - scheme: slate
    primary: indigo
    accent: pink
    toggle:
      icon: material/brightness-7
      name: Switch to light mode
  features:
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
    - navigation.tabs
    - navigation.instant
    - navigation.footer
    - navigation.tracking

plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

nav:
  # ---------- Home ----------
  - Home:
    - About me: index.md
  - Khoa Học:
    - Danh sách: Science/science-list.md
    - Vũ Trụ Trong Vỏ Hạt Dẻ:
      - Overview: Science/vu-tru-trong-vo-hat-de/0.md
      - CHƯƠNG 1 - LƯỢC SỬ VỀ THUYẾT TƯƠNG ĐỐI: Science/vu-tru-trong-vo-hat-de/1.md
      - CHƯƠNG 2 - HÌNH DÁNG CỦA THỜI GIAN: Science/vu-tru-trong-vo-hat-de/2.md
      - CHƯƠNG 3 - VŨ TRỤ TRONG MỘT VỎ HẠT: Science/vu-tru-trong-vo-hat-de/3.md
      - CHƯƠNG 4 - TIÊN ĐOÁN TƯƠNG LAI: Science/vu-tru-trong-vo-hat-de/4.md
      - CHƯƠNG 5 - BẢO VỆ QUÁ KHỨ: Science/vu-tru-trong-vo-hat-de/5.md
      - CHƯƠNG 6 - TƯƠNG LAI CỦA CHÚNG TA? CÓ THỂ LÀ STARTREK HAY KHÔNG?: Science/vu-tru-trong-vo-hat-de/6.md
      - CHƯƠNG 7 - MÀNG VŨ TRỤ MỚI: Science/vu-tru-trong-vo-hat-de/7.md
      - THUẬT NGỮ: Science/vu-tru-trong-vo-hat-de/8.md
  - Khoa Học Máy Tính:
    - Danh sách: Science/science-it-list.md
    - High Performance Browser Networking:
      - Overview:  Science/high-performance-browser-networking/0.md
      - Networking 101:
        - Primer on Latency and Bandwidth: Science/high-performance-browser-networking/1.md
        - Building Blocks of TCP: Science/high-performance-browser-networking/2.md
        - Building Blocks of UDP: Science/high-performance-browser-networking/3.md
        - Transport Layer Security (TLS): Science/high-performance-browser-networking/4.md
        - Introduction to Wireless Networks: Science/high-performance-browser-networking/5.md
        - Wifi: Science/high-performance-browser-networking/6.md
    - Hiểu biết sâu sắc về Android:
      - Overview:  Science/hieu-biet-sau-sac-ve-android/0.md
      - CHương 1 - Chuẩn bị trước khi đọc: Science/hieu-biet-sau-sac-ve-android/1.md
      - Chương 2 - Hiểu sâu sắc về JNI: Science/hieu-biet-sau-sac-ve-android/2.md
    - Competitive Programmer's Handbook:
      - Preface: Science/competitive-programmers-handbook/0.md
      - Part I - Basic technique:
        - "Chapter 1: Introduction": Science/competitive-programmers-handbook/1.md
        - "Chapter 2: Time complexity": Science/competitive-programmers-handbook/2.md
  - Triết Học:
    - Overview: Philosophy/philosophy.md
    - Chủ Nghĩa Khắc Kỷ:
        - Chủ Nghĩa Khắc Kỷ - Phong Cách Sống Bản Lĩnh Và Bình Thản:
          - Lời cảm ơn & Giới thiệu: Philosophy/chu-nghia-khac-ky-phong-cach-song-ban-linh-va-binh-than/0.md
          - "PHẦN MỘT: SỰ HÌNH THÀNH CỦA CHỦ NGHĨA KHẮC KỶ": Philosophy/chu-nghia-khac-ky-phong-cach-song-ban-linh-va-binh-than/1.md
          - "PHẦN HAI: CÁC KỸ THUẬT TÂM LÝ CỦA CHỦ NGHĨA KHẮC KỶ": Philosophy/chu-nghia-khac-ky-phong-cach-song-ban-linh-va-binh-than/2.md
          - "PHẦN BA: LỜI KHUYÊN CỦA CÁC NHÀ KHẮC KỶ": Philosophy/chu-nghia-khac-ky-phong-cach-song-ban-linh-va-binh-than/3.md
          - "PHẦN BỐN: CHỦ NGHĨA KHẮC KỶ TRONG CUỘC SỐNG HIỆN ĐẠI": Philosophy/chu-nghia-khac-ky-phong-cach-song-ban-linh-va-binh-than/4.md
    - Triết học hiện sinh:
        - Triết học hiện sinh:
          - Preface: Philosophy/triet-hoc-hien-sinh/0.md
          - Chương 1. TRIẾT HỌC HIỆN SINH LÀ GÌ?: Philosophy/triet-hoc-hien-sinh/1.md
          - Chương 2. NHỮNG ĐỀ TÀI CHÍNH CỦA TRIẾT HIỆN SINH: Philosophy/triet-hoc-hien-sinh/2.md
          - Chương 3. HAI NGÀNH CỦA PHONG TRÀO TRIẾT HIỆN SINH: Philosophy/triet-hoc-hien-sinh/3.md
          - Chương 4. KIERKEGAARD ÔNG TỔ HIỆN SINH TRUNG THỰC: Philosophy/triet-hoc-hien-sinh/4.md
          - Chương 5. NIETZSCHE ÔNG TỔ HIỆN SINH VÔ THẦN: Philosophy/triet-hoc-hien-sinh/5.md
          - Chương 6. HUSSERL ~ ÔNG TỔ VĂN CHƯƠNG TRIẾT LÝ HIỆN TƯỢNG HỌC: Philosophy/triet-hoc-hien-sinh/6.md
          - Chương 7. JASPERS HIỆN SINH VÀ SIÊU VIỆT: Philosophy/triet-hoc-hien-sinh/7.md
          - Chương 8. MARCEL HIỆN SINH VÀ HUYỀN NHIỆM: Philosophy/triet-hoc-hien-sinh/8.md
          - Chương 9. SARTRE - HIỆN SINH PHI LÝ: Philosophy/triet-hoc-hien-sinh/9.md
          - Chương 10. HEIDEGGER HIỆN SINH VÀ HIỆN HỮU: Philosophy/triet-hoc-hien-sinh/10.md
    - "Seneca - Những bức thư đạo đức":
      - "Seneca - Những bức thư đạo đức (Tập 1)":
        - Lời tựa: Philosophy/seneca-nhung-buc-thu-dao-duc-1/0.md
        - Bức thư số 1  : Philosophy/seneca-nhung-buc-thu-dao-duc-1/1.md
        - Bức thư số 2  : Philosophy/seneca-nhung-buc-thu-dao-duc-1/2.md
        - Bức thư số 3  : Philosophy/seneca-nhung-buc-thu-dao-duc-1/3.md
        - Bức thư số 4  : Philosophy/seneca-nhung-buc-thu-dao-duc-1/4.md
        - Bức thư số 5  : Philosophy/seneca-nhung-buc-thu-dao-duc-1/5.md
        - Bức thư số 6  : Philosophy/seneca-nhung-buc-thu-dao-duc-1/6.md
        - Bức thư số 7  : Philosophy/seneca-nhung-buc-thu-dao-duc-1/7.md
        - Bức thư số 8  : Philosophy/seneca-nhung-buc-thu-dao-duc-1/8.md
        - Bức thư số 9  : Philosophy/seneca-nhung-buc-thu-dao-duc-1/9.md
        - Bức thư số 10 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/10.md
        - Bức thư số 11 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/11.md
        - Bức thư số 12 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/12.md
        - Bức thư số 13 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/13.md
        - Bức thư số 14 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/14.md
        - Bức thư số 15 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/15.md
        - Bức thư số 16 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/16.md
        - Bức thư số 17 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/17.md
        - Bức thư số 18 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/18.md
        - Bức thư số 19 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/19.md
        - Bức thư số 20 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/20.md
        - Bức thư số 21 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/21.md
        - Bức thư số 22 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/22.md
        - Bức thư số 23 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/23.md
        - Bức thư số 24 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/24.md
        - Bức thư số 25 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/25.md
        - Bức thư số 26 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/26.md
        - Bức thư số 27 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/27.md
        - Bức thư số 28 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/28.md
        - Bức thư số 29 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/29.md
        - Bức thư số 30 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/30.md
        - Bức thư số 31 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/31.md
        - Bức thư số 32 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/32.md
        - Bức thư số 33 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/33.md
        - Bức thư số 34 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/34.md
        - Bức thư số 35 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/35.md
        - Bức thư số 36 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/36.md
        - Bức thư số 37 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/37.md
        - Bức thư số 38 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/38.md
        - Bức thư số 39 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/39.md
        - Bức thư số 40 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/40.md
        - Bức thư số 41 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/41.md
        - Bức thư số 42 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/42.md
        - Bức thư số 43 : Philosophy/seneca-nhung-buc-thu-dao-duc-1/43.md
  - Paper:
    - Danh sách: Paper/paper-list.md
    - Câu chuyện về crypto duy nhất bạn cần:
      - Overview: Paper/cau-chuyen-ve-crypto-duy-nhat-ban-can/0.md
      - I. Sổ cái - Bitcoin và Blockchain: Paper/cau-chuyen-ve-crypto-duy-nhat-ban-can/1.md
      - II. Nó có nghĩa là gì: Paper/cau-chuyen-ve-crypto-duy-nhat-ban-can/2.md
      - III. Hệ thống tài chính crypto: Paper/cau-chuyen-ve-crypto-duy-nhat-ban-can/3.md
      - IV. Sự tin tưởng - Tiền Bạc - Cộng đồng: Paper/cau-chuyen-ve-crypto-duy-nhat-ban-can/4.md
      - V. Hệ thống tài chính crypto: Paper/cau-chuyen-ve-crypto-duy-nhat-ban-can/5.md
      - VI. Sự tin tưởng - Tiền bạc - Cộng đồng: Paper/cau-chuyen-ve-crypto-duy-nhat-ban-can/6.md
    - Android Binder:
      - 1. Introduction: Paper/android-binder/0.md
      - 2. Multitasking, Processes and Threads: Paper/android-binder/1.md
      - 3. Android: Paper/android-binder/2.md
      - 4. Binder: Paper/android-binder/3.md
      - 5. Implementation of the Binder Framework: Paper/android-binder/4.md
      - 6. Example IPC Message Flow: Paper/android-binder/5.md
      - 7. Discussion: Paper/android-binder/6.md
    - Chủ nghĩa khắc kỷ, Đức hạnh và Sức khỏe tâm thần: Paper/stoic-virtue-and-mental-health.md
  - NonFig:
    - Danh sách: NonFig/nonfig-list.md
    - Thiên Nga Đen:
      - LỜI BẠT: NonFig/thien-nga-den/0.md
      - Phần Mở Đầu - XOAY QUANH BỘ LÔNG CHIM: NonFig/thien-nga-den/1.md
      - Phần Một - PHẢN THƯ VIỆN CỦA UMBERTO ECO HAY CÁCH CHÚNG TA TÌM KIẾM SỰ PHÊ CHUẨN: NonFig/thien-nga-den/2.md

extra_css:
  - stylesheets/theme.css
  - https://unpkg.com/katex@0/dist/katex.min.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true

extra_javascript:
  - scripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/dothanhdathp
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/tad.zeila?locale=vi_VN